openapi: 3.0.0
info:
  title: 'My First API'
  version: '0.1'
paths:
  /api/resource.json:
    get:
      operationId: bbd334a396905139ff272e5a21fb5d6e
      responses:
        '200':
          description: 'An example resource'
